# Generated by Django 4.1.1 on 2022-10-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="detalleventa", name="idProductos",),
        migrations.RemoveField(model_name="detalleventa", name="idVenta",),
        migrations.RemoveField(model_name="ingresarventa", name="idVehiculo",),
        migrations.RemoveField(model_name="pago", name="idVenta",),
        migrations.RemoveField(model_name="pedidoactivo", name="idPatente",),
        migrations.RemoveField(model_name="pedidoactivo", name="idPedido",),
        migrations.RemoveField(model_name="recarga", name="IdVehiculo",),
        migrations.RemoveField(model_name="vehiculooperativos", name="idEmpleado",),
        migrations.RemoveField(model_name="vehiculooperativos", name="patente",),
        migrations.DeleteModel(name="DetalleRecarga",),
        migrations.DeleteModel(name="DetalleVenta",),
        migrations.DeleteModel(name="Empleado",),
        migrations.DeleteModel(name="IngresarVenta",),
        migrations.DeleteModel(name="InventarioRecarga",),
        migrations.DeleteModel(name="InventarioVehiculo",),
        migrations.DeleteModel(name="Pago",),
        migrations.DeleteModel(name="Pedido",),
        migrations.DeleteModel(name="PedidoActivo",),
        migrations.DeleteModel(name="Recarga",),
        migrations.DeleteModel(name="VehiculoOperativos",),
    ]
