# Generated by Django 4.1.1 on 2022-10-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Persona",),
    ]
