# Generated by Django 4.1.1 on 2022-10-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0005_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventariovehiculo",
            old_name="fechaTecnica",
            new_name="fechaRevision",
        ),
        migrations.AlterField(
            model_name="inventariorecarga",
            name="idProducto",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
