# Generated by Django 4.1.1 on 2022-10-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionpedidos",
            "0006_rename_fechatecnica_inventariovehiculo_fecharevision_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(model_name="empleado", old_name="Rut", new_name="rut",),
    ]
