# Generated by Django 4.1.1 on 2022-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0007_rename_rut_empleado_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="estadoLaboral",
            field=models.CharField(default="Activo", max_length=100),
        ),
    ]
