# Generated by Django 4.1.1 on 2022-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0012_empleado_fechainicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recarga",
            name="fechaRecarga",
            field=models.DateField(blank=True, null=True),
        ),
    ]
