# Generated by Django 4.1.1 on 2022-11-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0013_alter_recarga_fecharecarga"),
    ]

    operations = [
        migrations.RemoveField(model_name="recarga", name="IdVehiculo",),
        migrations.DeleteModel(name="DetalleRecarga",),
        migrations.DeleteModel(name="Recarga",),
    ]
