# Generated by Django 4.1.1 on 2022-12-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0018_ingresarventa_fechaventita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingresarventa",
            name="fechaVentita",
            field=models.DateField(blank=True, null=True),
        ),
    ]
