# Generated by Django 4.1.1 on 2022-12-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0019_alter_ingresarventa_fechaventita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingresarventa",
            name="idVenta",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
