# Generated by Django 4.1.1 on 2022-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0022_alter_ingresarventa_idventa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingresarventa", name="fechaVenta", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ingresarventa",
            name="idVenta",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
