# Generated by Django 4.1.1 on 2022-12-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0023_alter_ingresarventa_fechaventa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingresarventa",
            name="fechaVenta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="IngresarVentas",
            fields=[
                (
                    "idVenta",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fechaVenta", models.DateField(blank=True, null=True)),
                (
                    "idVehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionpedidos.vehiculooperativos",
                    ),
                ),
            ],
        ),
    ]
