# Generated by Django 4.1.1 on 2022-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0024_alter_ingresarventa_fechaventa_ingresarventas"),
    ]

    operations = [
        migrations.CreateModel(
            name="ventitas",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fecha", models.DateField()),
            ],
        ),
    ]
