# Generated by Django 4.1.1 on 2022-12-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0025_ventitas"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventitas",
            name="idVehiculo",
            field=models.ForeignKey(
                default=99,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionpedidos.vehiculooperativos",
            ),
        ),
        migrations.AlterField(
            model_name="ventitas",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
