# Generated by Django 4.1.1 on 2022-12-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0027_alter_ventitas_fecha_alter_ventitas_idvehiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventitas",
            name="fecha",
            field=models.DateField(auto_now_add=True),
        ),
    ]
