# Generated by Django 4.1.1 on 2022-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0028_alter_ventitas_fecha"),
    ]

    operations = [
        migrations.DeleteModel(name="ventitas",),
    ]
