# Generated by Django 4.1.1 on 2022-12-01 05:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionpedidos", "0029_delete_ventitas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="idVenta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionpedidos.ingresarventas",
            ),
        ),
        migrations.AlterField(
            model_name="ingresarventas",
            name="fechaVenta",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
